[package]
name = "link-archive"
version = "0.1.0"
edition = "2018"
default-run = "link-archive"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
warp = "0.3"
rusqlite = "0.25"
quick_from = "0.1.0"
rust-argon2 = "0.8"
rand = "0.8"
jsonwebtoken = "7.2"
time = { version  = "0.3", features = ["macros", "formatting", "parsing"] }
cookie = "0.15"
handlebars = "4.1"

serde = { version = "*", features = ["derive"] }
bytes = "*"
url = "*"
http = "*"
