enum_discrim_align_threshold = 70
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 80
imports_granularity = "Module"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
space_before_colon = true
struct_field_align_threshold = 50
trailing_semicolon = false
use_field_init_shorthand = true
wrap_comments = true
